app/controllers/stations_controller.rb, app/models/station.rb, db/migrate/20180908195724_create_stations.rb, db/schema.rb, spec/features/user_can_see_stations_on_station_index_spec.rb
____ Reviewed
- [] Bug Fix
* added stations db real quick so we could progress with our work
closes # **
- [] My code has no unused/commented out code
Link: http://i.imgur.com/D5VHIxn.gif
=> Station DB Create

app/controllers/stations_controller.rb, app/models/station.rb, app/views/shared/_navigation.html.erb, app/views/stations/index.html.erb, app/views/stations/show.html.erb, config/routes.rb, db/migrate/20180908212140_add_slug_to_stations.rb, db/schema.rb, spec/features/user_can_see_station_details_on_station_show_page_spec.rb, spec/features/user_can_see_stations_on_station_index_spec.rb
__x__ Reviewed
- [] Bug Fix
* Stations index page, and Stations show page
closes #
Link: ![](https://media1.giphy.com/media/1d7F9xyq6j7C1ojbC5/giphy.gif)
=> Stations index and show

app/models/accessory.rb, db/migrate/20180908220957_create_accessories.rb, db/schema.rb
__x__ Reviewed
- [] Bug Fix
* Accessory Model and Table
closes #
Link: ![]https://media2.giphy.com/media/VacDNYowBxbva/giphy.gif
=> created accessory model and db

app/models/accessory.rb, app/models/station.rb, app/views/accessories/show.html.erb, db/migrate/20180909024739_add_retired_to_accessories.rb, db/schema.rb, spec/features/accessories/user_can_see_accessory_show_page_spec.rb, spec/features/accessories/user_sees_accessory_retired_spec.rb, spec/features/user_sees_trip_index_spec.rb, spec/models/station_spec.rb
__x__ Reviewed
* Added if/else to accessory to get retired value
* Fixed a broken image test
* Added accessory name to be unique
closes #17 
Link: ![](https://media1.giphy.com/media/Z543HuFdQAmkg/giphy.gif)
=> added retired to accessory, fixed img test, added uniq to accessory

app/controllers/application_controller.rb, app/controllers/bike_shop_controller.rb, app/controllers/carts_controller.rb, app/models/cart.rb, app/views/bike_shop/index.html.erb, app/views/carts/show.html.erb, app/views/shared/_navigation.html.erb, config/routes.rb, spec/features/bike_shop/user_sees_bike_shop_II_spec.rb, spec/features/bike_shop/user_sees_bike_shop_spec.rb, spec/features/user_sees_trip_index_spec.rb, spec/features/users/user_adds_stuff_to_cart_spec.rb, spec/models/cart_spec.rb
__x__ Reviewed
* Fixed a method that was broken for a dumb reason we couldn't figur out
closes #12 
Link: ![](https://media1.giphy.com/media/eXFACHFaS20Ss/giphy.gif)
=> Cart (whole team effort)

app/views/accessories/show.html.erb, app/views/bike_shop/index.html.erb, app/views/carts/show.html.erb, app/views/stations/index.html.erb, config/routes.rb, db/seeds.rb
__x__ Reviewed
* Add to cart from accessory page now works
* added thumbnail to cart
* added info to station page
* added link to accessory show from bike shop
* probably added some other stuff
closes #64 
Link: ![](https://media1.giphy.com/media/10FwycrnAkpshW/giphy.gif)
=> Fixing mistakes

app/views/conditions/index.html.erb, app/views/conditions/show.html.erb, db/seeds.rb
__x__ Reviewed
- [] Bug Fix
* description
adds labels to Conditions show and index pages, creates link from index to show pages, properly transfers data from csv to db.
closes # Waffle #56 
Link:
=> Update condition seeding

app/controllers/orders_controller.rb, app/controllers/users_controller.rb, app/models/accessory.rb, app/models/order.rb, app/models/order_accessory.rb, app/models/user.rb, app/views/orders/show.html.erb, app/views/users/dashboard.html.erb, config/routes.rb, db/migrate/20180910230756_create_orders.rb, db/migrate/20180910231535_create_order_accessories.rb, db/migrate/20180910235830_add_status_to_orders.rb, db/schema.rb, db/seeds.rb, spec/features/orders/user_sees_orders_on_dashboard_spec.rb, spec/models/order_spec.rb
__x__ Reviewed
- [] Bug Fix
* Created Order Table
* Create OrderAccessory Table
* Created order show page
* Created order views on dashboard
* Did all the things
closes #26 
Link: ![](https://media.giphy.com/media/BoW41ES14wUTvpAcvw/giphy.gif)
=> Making orders

app/assets/stylesheets/style.scss, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/views/sessions/new.html.erb, app/views/shared/_navigation.html.erb, app/views/users/new.html.erb, config/routes.rb, spec/features/users/user_creates_account_spec.rb, spec/features/users/user_logs_in_spec.rb, spec/features/users/user_logs_out_spec.rb
__X__ Wrote Tests
__X__ Reviewed
- [] Bug Fix
* User Logout, User Login & New User form styling, & relevant tests
closes #51 
closes #52 
Link: ![](https://media.giphy.com/media/3o7aDag3rYUx3sij6M/giphy.gif)
=> User Logout, User Login & New User form styling, & relevant tests

app/controllers/carts_controller.rb, app/models/cart.rb, app/views/carts/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/cart/a_user_can_remove_an_accessory_spec.rb
_x___ Wrote Tests
_x___ Implemented
_x___ Reviewed
- [] Bug Fix
* description
closes #14
*adds destroy method for cart controller
*adds flash warning for removing item for cart
*all test passing
Link:
=> 14 cart edit one

app/views/carts/show.html.erb, spec/features/cart/a_user_can_remove_an_accessory_spec.rb
__x__ Reviewed
* 1 inconsistent variable from merge
* 1 small typo in test
closes #
Link: ![](https://media3.giphy.com/media/IPosMMzCRthdK/giphy.gif)
=> fixed 2 typos from merge

app/controllers/checkout_controller.rb, app/controllers/users_controller.rb, app/models/checkout.rb, app/models/order.rb, app/views/carts/show.html.erb, config/routes.rb, db/seeds.rb, spec/features/cart/user_checks_out_cart_spec.rb
__x__ Reviewed
- [] Bug Fix
* description
closes #24 
Link:
=> User checkout ii

app/controllers/carts_controller.rb, app/views/carts/show.html.erb, config/routes.rb, spec/features/cart/a_user_can_increase_quantity_in_cart_spec.rb
__x__ Reviewed
- [] Bug Fix
* description Adds cart increase method and route, all tests passing.
closes #18 
Link:
=> 13 quantity increase

app/controllers/carts_controller.rb, app/models/cart.rb, app/views/carts/show.html.erb, config/routes.rb, spec/features/cart/a_user_can_decrease_items_in_cart_spec.rb, spec/models/cart_spec.rb
___x_ Wrote Tests
____x Reviewed
- [] Bug Fix
* description
closes #19 
*Adds feature test for decreasing items in cart
*adds method for removing accessory in cart model
*adds model test for removing accessory
*adds decrease cart route 
*ATP
Link:
=> 19 cart quantity decrease

app/controllers/admin/stations_controller.rb, spec/features/admins/stations/admin_creates_station_spec.rb
__X__ Wrote Tests
__X__ Reviewed
- [] Bug Fix
* After much toil, create finally passes. Another user story down!
closes #119
Link: ![](https://media.giphy.com/media/gYZ7qO81g4dt6/giphy.gif)
=> Admin create station

app/controllers/users_controller.rb, app/views/users/dashboard.html.erb, app/views/users/edit.html.erb, config/routes.rb, spec/features/users/admin_user_can_modify_own_data_spec.rb, spec/features/users/user_can_modify_own_data_spec.rb
___x_ Implemented
___x_ Reviewed
- [] Bug Fix
* description
user can modify own data
closes #88 
Link:
[https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwi7_6m-3rbdAhXCzIMKHe-GDr4QjRx6BAgBEAU&url=https%3A%2F%2Fgiphy.com%2Fgifs%2Fanimal-PgZdcUd6sTBZu&psig=AOvVaw1fCjX0hsR2ngwsDoaRX5MH&ust=1536885034545325](url)
=> Modify data access

app/views/bike_shop/index.html.erb, db/seeds.rb
__x__ Reviewed
* Added accessory retired to index
* Added default seeded users
closes #108 
Link:![](https://media0.giphy.com/media/KupdfnqWwV7J6/giphy.gif)
=> edited bike shop to show retired options

app/views/admin/stations/index.html.erb, app/views/admin/trips/index.html.erb, app/views/shared/_navigation.html.erb, app/views/stations/index.html.erb
____ Reviewed
- [] Bug Fix
* add special admin links so when a current user is an admin, the links they have will send them to other admin pages. 
closes #
- XX] This broke nothing
Link: ![](https://media.giphy.com/media/yFQ0ywscgobJK/giphy.gif)
=> Admin links

app/models/trip.rb, app/views/shared/_navigation.html.erb, app/views/trips/dashboard.html.erb, app/views/trips/index.html.erb, app/views/trips/show.html.erb, db/schema.rb, spec/features/trips/trips_dashboard_spec.rb
____ Implemented
____x Reviewed
* description
Changes minutes to seconds for trips, adds trips dash link, adds round to duration methods.
closes #
Link: ![tenor](https://user-images.githubusercontent.com/25314178/45465472-95f44080-b6d2-11e8-8ce4-7b03703e2c2c.gif)
=> 83 trips dashboard stats

app/controllers/admin/trips_controller.rb, app/views/admin/stations/show.html.erb, app/views/admin/trips/index.html.erb, app/views/admin/trips/show.html.erb, config/routes.rb, spec/features/admins/stations/admin_edits_station_spec.rb, spec/features/admins/trips/admin_deletes_trip_spec.rb, spec/features/admins/trips/admin_views_admin_trips_index_page_spec.rb, spec/features/admins/trips/admin_views_admin_trips_show_page_spec.rb
__X__ Wrote Tests
__X__ Reviewed
- [] Bug Fix
* This adds admin delete functionality to admin trips index & show
* This also adds missing label  for admin trip show
* I have also begun working on admin edit/update functionality on admin trips index & show, but I will push that up in a separate branch once it's all good to go. 
closes #114 
closes #127 
Link: ![](https://media.giphy.com/media/llZ2R6hwJVxWE/giphy.gif)
=> Admin trip delete 

app/controllers/checkout_controller.rb, app/views/orders/show.html.erb, app/views/shared/_navigation.html.erb, app/views/users/dashboard.html.erb, config/routes.rb, db/seeds.rb, spec/features/cart/a_user_can_decrease_items_in_cart_spec.rb, spec/features/cart/a_user_can_increase_quantity_in_cart_spec.rb, spec/features/cart/a_user_can_remove_an_accessory_spec.rb, spec/features/cart/user_checks_out_cart_spec.rb, spec/features/users/user_adds_stuff_to_cart_spec.rb
__x__ Reviewed
- [] Bug Fix
* description
seeds data for orders on test accounts.
closes #111 
Link: [https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwja5LH2sLfdAhWCw4MKHZmpAZIQjRx6BAgBEAU&url=https%3A%2F%2Ftenor.com%2Fsearch%2Ffish-gifs&psig=AOvVaw2WYB6ikgvtrsdRRorQ4Xkv&ust=1536907547537862](url)
=> Seed orders

app/controllers/admin/stations_controller.rb, app/controllers/checkout_controller.rb, app/views/admin/stations/index.html.erb, app/views/orders/show.html.erb, app/views/shared/_navigation.html.erb, app/views/stations/dash.html.erb, app/views/users/dashboard.html.erb, config/routes.rb, db/seeds.rb, spec/features/cart/a_user_can_decrease_items_in_cart_spec.rb, spec/features/cart/a_user_can_increase_quantity_in_cart_spec.rb, spec/features/cart/a_user_can_remove_an_accessory_spec.rb, spec/features/cart/user_checks_out_cart_spec.rb, spec/features/users/user_adds_stuff_to_cart_spec.rb
__x__ Reviewed
- [] Bug Fix
* description
creates navigation to stations dashboard
closes #113 
Link: [https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwjUtfCDt7fdAhVrzIMKHWjRDlcQjRx6BAgBEAU&url=https%3A%2F%2Ftenor.com%2Fview%2Fghostbusters-ghostbusters2016-chick-it-out-chris-hemsworth-gif-5471561&psig=AOvVaw3r7Wc-H7TC2FzPjufaWB3y&ust=1536909188532066](url)
=> Stations dash revised

app/views/shared/_navigation.html.erb, app/views/stations/index.html.erb, app/views/trips/index.html.erb, config/routes.rb
__x__ Reviewed
* moved dashboards to index's
* added working trips route
closes #135 
Link: ![](https://media0.giphy.com/media/AnQ81pE1JaUOA/giphy.gif)
=> Trip route fix

app/controllers/users_controller.rb, app/views/shared/_navigation.html.erb, config/routes.rb
__x__ Reviewed
* User can no longer edit another users infor
closes #136 
- [] My code has no unused/commented out code
Link: ![](https://media3.giphy.com/media/3o72F8MJL7pZMPOeyI/giphy.gif)
=> certainly did a thing

app/views/shared/_navigation.html.erb
____ Reviewed
- [] Bug Fix
* description
closes #
- [] My code has no unused/commented out code
Link: ![](https://media.giphy.com/media/wtYoiNRitOMiA/giphy.gif)
=> update nav bar links

app/controllers/checkout_controller.rb, app/controllers/orders_controller.rb, spec/features/cart/user_checks_out_cart_spec.rb
__x__ Reviewed
* description pluralization
closes #140 
Link:
=> Order flash message pluralize

spec/features/cart/user_checks_out_cart_spec.rb
__x__ Reviewed
* description a test fix.
closes #
Link:
=> no change.

app/controllers/admin/trips_controller.rb, spec/features/admins/trips/admin_edits_trip_page_spec.rb
__X__ Wrote Tests
__X__ Reviewed
- [] Bug Fix
* admin can now update trips
closes #166
Link: ![](https://media.giphy.com/media/1TOSaJsWtnhe0/giphy.gif)
=> Admin update trip

spec/features/users/user_cant_modify_others_data_spec.rb
____ Implemented
__x__ Reviewed
* description
makes sure a user cannot access another's edit pages.
closes #27 
Link:
=> cannot modify another's data spec.

app/controllers/admin/dashboards_controller.rb, app/views/admin/dashboards/show.html.erb, spec/features/users/admin_user_can_modify_own_data_spec.rb, spec/features/users/cant_access_admin_pages_spec.rb
__x__ Reviewed
- [] Bug Fix
* description
tests for denial access to admin pages and functionality
closes #20 
Link:
=> Cant access admin

app/controllers/conditions_controller.rb, app/models/trip.rb, app/views/conditions/dashboard.html.erb, spec/features/admins/admin_dashboard_spec.rb, spec/models/trip_spec.rb
__x__ Reviewed
- [] Bug Fix
* wrote tests for and dried up trips
* wrote tests for admin dashboard
closes #148 
Link: ![](https://media3.giphy.com/media/NmcjVmtqWo5oY/giphy.gif)
=> Fine ill make tests you babies

app/controllers/accessories_controller.rb, app/views/accessories/index.html.erb, app/views/admin/dashboards/show.html.erb, config/routes.rb, spec/features/accessories/admin_can_see_all_accessories_spec.rb
__x__ Reviewed
- [] Bug Fix
* description
Starting to create admin accessory page.
closes #
Link:
`https://i.gifer.com/cED.mp4`
=> Link view accessories

app/views/shared/_navigation.html.erb
____ Reviewed
- [] Bug Fix
* make logo link to user dashboard if a user is logged in, but link to root if not 
closes #
Link: ![](https://media.giphy.com/media/gSotjAQJmPTJm/giphy.gif)
=> make logo link differently for a current user

app/models/station.rb, app/views/stations/show.html.erb, spec/features/admins/admin_dashboard_spec.rb, spec/features/stations/user_sees_stats_on_station_show_page_spec.rb, spec/features/users/cant_access_admin_pages_spec.rb
__x__ Reviewed
- [] Bug Fix
* Shows stats on station show page like the dumb user story tells us to .
* I'll stab someone over this.
closes #84 
Link: ![](https://media1.giphy.com/media/3ohfFgmNZhta4rXiXm/giphy.gif)
=> we're really doing it oh wow oh wow oh wow

app/controllers/orders_controller.rb, app/views/admin/dashboards/show.html.erb, app/views/orders/show.html.erb, config/routes.rb, spec/features/admins/admin_dashboard_spec.rb
__x__ Reviewed
* Changed cancel to change status instead of delete
* fixed one test
closes #186 
Link: ![](https://media.giphy.com/media/1O0ybGfU6nKtFGgs6s/giphy.gif)
=> Fixed cancel button to change status instead of delete

app/views/bike_shop/index.html.erb, spec/features/accessories/admin_can_see_all_accessories_spec.rb, spec/features/bike_shop/user_sees_bike_shop_II_spec.rb, spec/features/cart/a_user_can_decrease_items_in_cart_spec.rb, spec/features/cart/a_user_can_increase_quantity_in_cart_spec.rb, spec/features/cart/a_user_can_remove_an_accessory_spec.rb, spec/features/cart/user_checks_out_cart_spec.rb, spec/features/cart/user_sees_cart_contents_spec.rb, spec/features/users/user_adds_stuff_to_cart_spec.rb, spec/models/station_spec.rb
__x__ Reviewed
* description Bad tests.
closes #
Link:
=> Test fixes

app/views/admin/accessories/edit.html.erb, config/routes.rb, spec/features/accessories/admin_can_edit_accessory_spec.rb, spec/features/accessories/admin_can_see_all_accessories_spec.rb, spec/models/station_spec.rb
___x_ Implemented
__x__ Reviewed
- [] Bug Fix
* description tests for accessory edit by admin
closes #
Link: ![](https://media.giphy.com/media/mCRJDo24UvJMA/giphy.gif)
WIP
=> Accessory edit

app/controllers/admin/accessories_controller.rb, config/routes.rb, spec/features/accessories/admin_can_edit_accessory_spec.rb
___x_ Implemented
___x_ Reviewed
- [] Bug Fix
* description test fix
closes #
Link:
=> Testing cont

app/controllers/admin/stations_controller.rb, app/controllers/stations_controller.rb, app/models/station.rb, app/views/admin/accessories/_form.html.erb, app/views/stations/show.html.erb
____ Implemented
_X___ Reviewed
- [] Bug Fix
* fix station create method and remove unneeded slug field
closes #204 
closes #202
Link: ![](https://media.giphy.com/media/pO4UHglOY2vII/giphy.gif)
=> Fix station create

app/views/conditions/dashboard.html.erb, app/views/conditions/show.html.erb, app/views/trips/dashboard.html.erb
__x__ Reviewed
- [] Bug Fix
* description
adds units for conditions for readability
closes #
Link:
=> updates values for condition data.

app/views/trips/dashboard.html.erb, spec/features/trips/trips_dashboard_spec.rb
_x___ Wrote Tests
_x___ Reviewed
* description 
*fixes formatting for monthly breakdowns
*ATP
closes #205 
Link: ![giphy 8](https://user-images.githubusercontent.com/25314178/45725199-e5c18480-bb76-11e8-92ef-356c673a864d.gif)
=> Last fixes
